### ISSUE TITLE
Share not working!

### ISSUE THREAD

**Issue by uzza1hossain** [Alt-er/obsidian-sync-share#1]
First of all it’s create link like https://example.com/share//uuid
And when I visit the link it’s a 404
I tried with https://example.com/share/uuid still same.
Any idea what I did wrong or how can I fix this?

**Comment by Alt-er** [comment]
May I ask if you are using a service you built yourself?
My service is not externally accessible at the moment

**Comment by uzza1hossain** [comment]
It’s my own server. I deployed using docker and sync working fine but share shows not found and url is miss configured

**Comment by Alt-er** [comment]
Did you succeed in logging in to the obsidian plugin?

If so, can you check to see if you can see your sharing history?

**Comment by Alt-er** [comment]
![image](https://github.com/Alt-er/obsidian-sync-share/assets/18004903/fc35d3bb-d0dc-48c6-914f-2acbb373f952)

Did you succeed in logging in here?

**Comment by uzza1hossain** [comment]
My bad. It was not on the doc. It’s working now.
Thanks for prompt reply. 

Is there any way to sync .obsidian folder? And how remote git work?

**Comment by Alt-er** [comment]
Sorry , it's not possible to synchronize .obsidian folders at the moment , it may be added later .

The remote git function is just a remote backup, you can send a copy of the data to the remote git every time you synchronize data, to ensure that the server data loss can be retrieved data

**Comment by uzza1hossain** [comment]
Thank you
