### ISSUE TITLE
When a file is changed in two devices before syncing, does not merge

### ISSUE THREAD

**Issue by nikpelgr** [Alt-er/obsidian-sync-share#11]
Hi,
If I try to sync between two devices a specific file that has been changed on both systems, then after syncing the changes of the last one are kept hence we have data loss. No merging is made (maybe is not needed) but it as second file with the suffix (-conflict) could be created in order to prevent the data loss.

**Comment by Alt-er** [comment]
The synchronization principle of this plug-in is to use the file modification time as the main basis. It cannot handle conflicts like git. Generally, the probability of multiple terminals modifying the same file at the same time is very low. Just set an appropriate synchronization time, so without thinking

**Comment by nikpelgr** [comment]
Right. 
I just synced today's note and already lost data.

**Comment by Alt-er** [comment]
Are there any bugs in using it?

**Comment by nikpelgr** [comment]
Fine. Keep it for your self. Just uninstalled. Regards
