### ISSUE TITLE
Remove notification

### ISSUE THREAD

**Issue by martin-arg** [Alt-er/obsidian-sync-share#13]
Good morning, first of all I wanted to tell you that I love the plug-in. 
But I wanted to know if it is possible to remove the notification of successful synchronisation.
I would like to sync every minute, but when I open a menu the notification closes it, which becomes very annoying, and makes it impractical to sync in 1m.

**Comment by Alt-er** [comment]
Thank you for your use. What do you think about adding a `Show Notifications` switch in the settings?

**Comment by martin-arg** [comment]
Yes, that would be very useful, so everyone can choose what they want.
Thanks

**Comment by Alt-er** [comment]
This feature has been added, please update the plug-in version

<img width="815" alt="image" src="https://github.com/Alt-er/obsidian-sync-share/assets/18004903/265f5ab2-9e50-4d10-991d-3d502ae4579c">

**Comment by martin-arg** [comment]
Thank you
