### ISSUE TITLE
Synchronise installed plugins

### ISSUE THREAD

**Issue by martin-arg** [Alt-er/obsidian-sync-share#14]
Obsidian's synchronisation service allows you to synchronise which plug-ins are installed so that all clients have the same ones. Can this be replicated? 
Yes, I see that the configuration files are synchronised.

**Comment by Alt-er** [comment]
It is currently not possible to synchronize installed plug-ins. Other synchronization (unofficial) plug-ins do not seem to have this function. I am not sure whether synchronizing plug-in files directly will cause any unexpected problems (such as requiring a restart to take effect).

**Comment by martin-arg** [comment]
I don't know about other plugins, but before the official sync I used an external webdab and it synced the plugins without any problems.

**Comment by Alt-er** [comment]
This function can be implemented, and other users have indeed mentioned this requirement before, but I cannot guarantee whether unexpected things will happen when synchronizing plug-in data. You need to bear the consequences yourself. If it is acceptable, I will provide this function in the next version.

**Comment by martin-arg** [comment]
What do you think could go wrong?
When I use my sync solution I sync the entire vault including .obsidian and I never have a problem. Except when I have two different Obsidian open at the same time, the same file.
You can also make this feature optional?

**Comment by Alt-er** [comment]
Under normal circumstances, there will be no problem, but there is a very small probability that there will be a problem, because the plug-ins in all your devices will share the same configuration and data, which will cause some things to be shared that should not be shared.

For example, the token obtained after successful login in the plug-in is originally unique for each device. Now all devices use the same token, which may cause problems.

**Comment by martin-arg** [comment]
I feel a bit guilty for asking so much. But looking at the sync plugin again, you could implement a full sync with the excluded option.

**Comment by Alt-er** [comment]
in development

**Comment by Alt-er** [comment]
The new version has been released. Please update the plug-in and back-end services. Please back up the data before synchronizing the obsidian configuration directory/plug-in directory. If you encounter any problems, please contact me.

**Comment by wangweitung** [comment]
> The new version has been released. Please update the plug-in and back-end services. Please back up the data before synchronizing the obsidian configuration directory/plug-in directory. If you encounter any problems, please contact me.

add device name to config folder name , in order to avoid file conflicts?

**Comment by Alt-er** [comment]
> > The new version has been released. Please update the plug-in and back-end services. Please back up the data before synchronizing the obsidian configuration directory/plug-in directory. If you encounter any problems, please contact me.
> 
> add device name to config folder name , in order to avoid file conflicts?

Can you elaborate on your needs?

**Comment by wangweitung** [comment]
> > > The new version has been released. Please update the plug-in and back-end services. Please back up the data before synchronizing the obsidian configuration directory/plug-in directory. If you encounter any problems, please contact me.
> > 
> > 
> > add device name to config folder name , in order to avoid file conflicts?
> 
> Can you elaborate on your needs?

device Redmi config backup to
.obsidian-Redmi   , which can be set in obsidian-setting-about

device iPhone config backup to
.obsidian-iPhone, which can be set in obsidian-setting-about

**Comment by Alt-er** [comment]
> > > > The new version has been released. Please update the plug-in and back-end services. Please back up the data before synchronizing the obsidian configuration directory/plug-in directory. If you encounter any problems, please contact me.
> > > 
> > > 
> > > add device name to config folder name , in order to avoid file conflicts?
> > 
> > 
> > Can you elaborate on your needs?
> 
> device Redmi config backup to .obsidian-Redmi , which can be set in obsidian-setting-about
> 
> device iPhone config backup to .obsidian-iPhone, which can be set in obsidian-setting-about

This seems achievable, but it involves a different logic than what we currently have. It might require a redevelopment. I'll need to give it some more thought because I've been quite busy lately. Once the feature stabilizes, we can consider adding this enhancement.

**Comment by martin-arg** [comment]
Yes, after the last update I don't know if it's the plugin or the backend, I have problems synchronizing my files between my devices. Changes do not propagate to other devices. And I keep getting the message that I can't sync because another device is syncing, even though all my other devices are turned off. I deactivate config sync to see if this resolve the problem.

**Comment by Alt-er** [comment]
> Yes, after the last update I don't know if it's the plugin or the backend, I have problems synchronizing my files between my devices. Changes do not propagate to other devices. And I keep getting the message that I can't sync because another device is syncing, even though all my other devices are turned off. I deactivate config sync to see if this resolve the problem.

An error occurs during the synchronization process, which will cause other devices to fail to synchronize successfully. If it fails for more than half an hour, it will be automatically unlocked, or it can be unlocked by deleting the `user_store/username/sync_lock` file.
