### ISSUE TITLE
Android pad login adjustment needed

### ISSUE THREAD

**Issue by wangweitung** [Alt-er/obsidian-sync-share#15]
![123](https://github.com/Alt-er/obsidian-sync-share/assets/8080125/c9dddbab-1d05-4abb-97da-66c382a2cd4b)

device type：xiaomi pad 5

problem：unable to see the user name typed in

**Comment by Alt-er** [comment]
This is the default style of the plug-in. I have not made any modifications. I have simulated various resolutions and I don’t seem to find this phenomenon. Does this problem affect login?

**Comment by wangweitung** [comment]
> Does this problem affect login?

Yes, because I can not see what I typed in the username section.
I tried several times before I successfully login.

**Comment by wangweitung** [comment]
But it works fine on Android phone , still wonder why this happens only on my mipad5.

**Comment by Alt-er** [comment]
Which version of the client are you using? Please try to use the latest version to see if there are any problems

**Comment by wangweitung** [comment]
> Which version of the client are you using? Please try to use the latest version to see if there are any problems

both obsidian and mipad5 are already up to date

**Comment by Alt-er** [comment]
@wangweitung  The plug-in has been updated, please upgrade the plug-in and check if the problem is resolved.

**Comment by wangweitung** [comment]
> @wangweitung  The plug-in has been updated, please upgrade the plug-in and check if the problem is resolved.

![IMG_20231024_195928.jpg](https://github.com/Alt-er/obsidian-sync-share/assets/8080125/7fa0cdc3-1ff8-4cf3-8cd2-2445aab5485c)

It works perfectly now,thanks for your great work.
