### ISSUE TITLE
self define the  sharing url 

### ISSUE THREAD

**Issue by wangweitung** [Alt-er/obsidian-sync-share#16]
could the following feature supported？

![图片](https://github.com/Alt-er/obsidian-sync-share/assets/8080125/6d8af52c-d73d-49a5-9c91-b9700103e3b9)

**Comment by Alt-er** [comment]
It is theoretically possible, but it is not recommended. If you only need to customize the URL for a few special shares, you can change the file name corresponding to the uuid in the `share` directory of the server to the name you need.

**Comment by wangweitung** [comment]
> It is theoretically possible, but it is not recommended. If you only need to customize the URL for a few special shares, you can change the file name corresponding to the uuid in the `share` directory of the server to the name you need.

you mean `change the file name` ->  `change the folder name`.

I tried , it worked, thanks~
