### ISSUE TITLE
Problems with syncing

### ISSUE THREAD

**Issue by martin-arg** [Alt-er/obsidian-sync-share#18]
Since the last server upgrade (maybe plugin too) I've been having serious problems syncing the vault. Firstly, I keep getting the message "Other clients are in process of synchronization" when I'm sure there aren't any.
Secondly, since last Friday, I have lost some files from a folder, and I have copied them back from a backup, and when the plugin syncs they are deleted again.
I have already restarted the server. I'm not really sure if there's anything else I can try.

**Comment by Alt-er** [comment]
I'm very sorry. Have you turned on the synchronization profile function? Generally, synchronization conflicts occur because there was a problem with the last synchronization. Did you see any errors during synchronization?

**Comment by martin-arg** [comment]
I already disable profile synchronization and I don't see anything strange. What can I do to help?

**Comment by Alt-er** [comment]
I would like to ask if the synchronization configuration file was enabled when the error occurred before. I need to determine whether the problem is caused by the synchronization configuration file.

**Comment by martin-arg** [comment]
No It was't. I disable the sync of the config file.

**Comment by martin-arg** [comment]
Also, even though I only have this plug-in active in one client, I'm still getting the message "Other clients are synchronising".

**Comment by Alt-er** [comment]
Is your server up to date? (1.2.0)
You can open http://your server
Scroll to the bottom and the version number will be displayed.

**Comment by Alt-er** [comment]
If you are sure it is the latest version, can you do a test for me?
1. Delete the `user_store/{user}/sync_lock` file on the server, if it exists
2. Resynchronize to see if errors occur

**Comment by martin-arg** [comment]
> Is your server up to date? (1.2.0) You can open http://your server Scroll to the bottom and the version number will be displayed.

yes

**Comment by martin-arg** [comment]
> If you are sure it is the latest version, can you do a test for me?
> 
>     1. Delete the `user_store/{user}/sync_lock` file on the server, if it exists
> 
>     2. Resynchronize to see if errors occur

It exists, I delete it and try to sync again.
I enable the notification in Obsidian and I never get the sync complete notification. Also, the file is still there.

**Comment by Alt-er** [comment]
~~Do you mean that after deleting the lock file, the file was regenerated after resynchronization was completed?
Please delete the lock file, resynchronize, and turn on the synchronization notification to see if there is a prompt that the synchronization is completed.~~
If there is no prompt that synchronization is completed, an error occurred during the synchronization process.

Are you using a reverse proxy program such as nginx? They may limit the maximum file size, causing synchronization to fail.

if there is not:

You can use `docker logs obsidian-sync-share-server` to check the logs to see if there are any errors. If it is convenient, please send me the error logs to analyze the reasons.

**Comment by martin-arg** [comment]
> Are you using a reverse proxy program such as nginx? They may limit the maximum file size, causing synchronization to fail.

Yes, I am, is there a way to check this?

**Comment by martin-arg** [comment]
[obsidian-sync-share-server_logs.txt](https://github.com/Alt-er/obsidian-sync-share/files/13364233/obsidian-sync-share-server_logs.txt)

**Comment by martin-arg** [comment]
For test purposes, I deleted all files over 4mb, there were few and old.  But no changes.

**Comment by Alt-er** [comment]
Please delete the lock file, open the development window of obsidian, and then resynchronize to see if there are any errors.

<img width="305" alt="image" src="https://github.com/Alt-er/obsidian-sync-share/assets/18004903/1f2aab1e-7243-4ba2-aff8-dcaa071a7f76">

<img width="629" alt="image" src="https://github.com/Alt-er/obsidian-sync-share/assets/18004903/fc51ab78-7b02-4194-83fd-68a004eb3d4f">


If it is convenient, please send a screenshot to me.

**Comment by Alt-er** [comment]
If there is something you don't understand, please feel free to tell me, I have time to solve the problem now

**Comment by Alt-er** [comment]
As far as I know, the default maximum upload file size of nginx is 1mb

You can try changing it to:
`client_max_body_size 1000m;`

**Comment by martin-arg** [comment]
![imagen](https://github.com/Alt-er/obsidian-sync-share/assets/7675317/1142a866-1216-4457-a694-b3bb3540817c)

**Comment by Alt-er** [comment]
I have roughly located the place where the problem occurred, but I found no logical errors after checking the code, so I added some log printing. Can you help me test it again? Thank you very much.

1. Replace main.js. There is a hidden .obsidian directory in your vault directory. Replace it.
`{vault_dir}/.obsidian/plugins/notes-sync-share/main.js`
2. After deleting the lock file, resynchronize, and open the obsidian development window to view the detailed error log

[main.js.zip](https://github.com/Alt-er/obsidian-sync-share/files/13371627/main.js.zip)

**Comment by Alt-er** [comment]
I'm very sorry for affecting your normal use.

**Comment by martin-arg** [comment]
> I'm very sorry for affecting your normal use.

Don't worry, you are working for free for a program that is free. These things happened.

**Comment by martin-arg** [comment]
![imagen](https://github.com/Alt-er/obsidian-sync-share/assets/7675317/6279ccd0-72f7-4649-9d71-3af01d5c67af)

**Comment by Alt-er** [comment]
It doesn't seem to be taking effect. I seem to have forgotten to mention that you need to restart obsidian after replacing the file for it to take effect.

Please restart obsidian and repeat the above operations.

**Comment by Alt-er** [comment]
> > I'm very sorry for affecting your normal use.
> 
> Don't worry, you are working for free for a program that is free. These things happened.

Thanks for understanding, I appreciate your help.

**Comment by martin-arg** [comment]
Something strange happened, I copied the file and restarted Obsidian and synced, lots of stuff appeared, I don't know why, but I deleted and synced again and took the screenshot.
The strange thing is that the main file reverts back to the original as the config file sync where enabled and it's not.
![imagen](https://github.com/Alt-er/obsidian-sync-share/assets/7675317/01bffb27-e731-46f3-9996-e5789772b25f)
I attach the picture so as not to look crazy.

**Comment by martin-arg** [comment]
![imagen](https://github.com/Alt-er/obsidian-sync-share/assets/7675317/35c5ac39-f02c-435c-bcc0-803dffa185ea)

![imagen](https://github.com/Alt-er/obsidian-sync-share/assets/7675317/29d0f0a4-4e54-4756-b3df-a2c035888887)
 And so on for a few more files.

**Comment by martin-arg** [comment]
This last sync the sync file was erased.

**Comment by martin-arg** [comment]
Also the file which is complaining about is not capitalised is permissions.md

**Comment by Alt-er** [comment]
Only the red text is printed by my plug-in, the rest are logs from other plug-ins.

Judging from the printed information, I checked my code and there was no problem. Is there a bug in Obsidian's API?

After the replacement, the synchronization was successful because the plug-in continued to execute when it encountered an error, instead of interrupting, so it was able to work normally.

**Comment by Alt-er** [comment]
> Also the file which is complaining about is not capitalised is permissions.md

After your reminder, I seem to understand the cause of the problem.
The logic of the plug-in is to create the file when the file does not exist, but the operating system's files are not case-sensitive, resulting in a file that does not exist when checked, but cannot be created.

**Comment by Alt-er** [comment]
Is this the case?

There is a Permissions.md file on the server
There is a file called permissions.md on your local machine

**Comment by martin-arg** [comment]
Yes, for this reason I'm trying to normalise the file name, to lower case and use dot insted of spaces.

**Comment by Alt-er** [comment]
Now that the cause of the problem has been determined, I need time to see how to solve this problem perfectly. After solving it, I will notify you of the update. Now you can use the plug-in normally, because now the same error will not interrupt synchronization. .

**Comment by martin-arg** [comment]
Thank you, if there is any test you would like me to do, please let me know.

**Comment by Alt-er** [comment]
> Thank you, if there is any test you would like me to do, please let me know.

ok thanks

**Comment by martin-arg** [comment]
One more question, is there anyway to push changes form the client to the server? I make some changes in the client, but when I sync, the server deletes this change. I restore the files on the client and again the server deletes these changes.

**Comment by Alt-er** [comment]
The plug-in uses the modification time to determine the latest data of the file. The new one will overwrite the old one. The situation you are talking about should be that the time on the server is relatively new. Please check the modification times of client and server files.

**Comment by martin-arg** [comment]
The folders have been deleted from the server for testing purposes.

**Comment by martin-arg** [comment]
Sorry, let me explain, I deleted the folder from the client and they were deleted from the server. Now I restore the folder, but when I synchronise they are deleted again.

**Comment by Alt-er** [comment]
Yes, if it is an empty folder and has been deleted before, it will always be deleted. You have 2 ways to solve it.
1. Put a file in the folder. If there is a file, the folder will not be deleted.
2. Delete the `user_store/{user}/server_delete_history` file on the server

**Comment by martin-arg** [comment]
Ok, this is asking too much, but in the future can you add the option to push or pull a sync manually?

**Comment by Alt-er** [comment]
> this is asking too much

The two methods provided above can be solved by choosing one. Generally, you only need to ensure that there are files in the folder.

> but in the future can you add the option to push or pull a sync manually?

Isn’t there a manual synchronization function? Or did I misunderstand the meaning?

**Comment by Alt-er** [comment]
As for why deleted empty folders are always deleted, you can look at the synchronization algorithm.
[synchronization algorithm](https://github.com/remotely-save/remotely-save/blob/master/docs/sync_algorithm_v2.md)

**Comment by martin-arg** [comment]
The folder was empty, I restore the folder and all the file inside, but the sync deleted again. Yes there is a manual sync button. The push and pull option would to force to push changes even when the algorithm says otherwise, the same with the pull, I delete some files locally, and I want to restore from the server, for example.

**Comment by Alt-er** [comment]
Let me sort out the questions:

After deleting the folder and the files in the folder locally, restore the folder and the internal files from the backup (no modifications to the files), and then synchronize the files. The folder just restored is deleted again.

do you mean this?

in the case of

Please temporarily delete the files on the server first: `user_store/{user}/server_delete_history`

Let me see if there is a good way to automatically solve this problem

**Comment by Alt-er** [comment]
> Let me sort out the questions:
> 
> After deleting the folder and the files in the folder locally, restore the folder and the internal files from the backup (no modifications to the files), and then synchronize the files. The folder just restored is deleted again.
> 
> do you mean this?
> 
> in the case of
> 
> Please temporarily delete the files on the server first: `user_store/{user}/server_delete_history`
> 
> Let me see if there is a good way to automatically solve this problem

This problem has been solved and will take effect in the next version

The solution is to modify the last modification time of the file to the current time when restoring the file, which can solve the problem.

The reason for this problem is that the modification time of the file does not change when the file is restored, and the server has remembered that you have deleted the file before, so it will ask the client to delete it.
(Server deletion time > file last modification time)

**Comment by Alt-er** [comment]
New version has been released

**Comment by martin-arg** [comment]
After upgrading I receive this, over and over again 
![imagen](https://github.com/Alt-er/obsidian-sync-share/assets/7675317/e64eb9e0-307d-4f74-9278-0aaf03c2301c)
There are more, but I can capture them before they vanish.
Also this
![imagen](https://github.com/Alt-er/obsidian-sync-share/assets/7675317/91a68cd4-38bf-4bbb-ad88-15874d2ebcc1)

**Comment by Alt-er** [comment]
Now if you find that the same file name (case-insensitive) appears on the server and the local file, this error will occur, and you need to change it to the same name as the server.

Because the server is case-sensitive, the easiest way is to delete these local files with the same name and then resynchronize them. The plug-in will automatically download these files.

I tried to automatically solve this problem, but I found that this cannot be solved perfectly because different operating systems are different:
linux android case sensitive
windows macos case-insensitive

As a result, there is no way to automatically solve it. For example, if there is a and A files on Linux, unexpected problems will occur if the files are synchronized to Windows.

**Comment by Alt-er** [comment]
If you have good ideas and suggestions, we can discuss them

**Comment by martin-arg** [comment]
> Because the server is case-sensitive, the easiest way is to delete these local files with the same name and then resynchronize them. The plug-in will automatically download these files.

I try this and I didn't work. The pluginn deletes the files in the server.

**Comment by martin-arg** [comment]
> If you have good ideas and suggestions, we can discuss them

This is why I suggest the push and pull options. ex: with pull you can force the download of the files as in the server. Or with push you can force to upload the as in the host.

**Comment by martin-arg** [comment]
Personally, I just resolve my problems renaming and deleting files. For something more general, I don't like the idea, but you can make the sync case-insensitive.

**Comment by Alt-er** [comment]
> > Because the server is case-sensitive, the easiest way is to delete these local files with the same name and then resynchronize them. The plug-in will automatically download these files.
> 
> I try this and I didn't work. The pluginn deletes the files in the server.

Under normal circumstances, files on the server should not be deleted. Is your server operating system Linux?

If that doesn't work, you can consider deleting the files on the server and resynchronizing them from the client.

**Comment by Alt-er** [comment]
> > If you have good ideas and suggestions, we can discuss them
> 
> This is why I suggest the push and pull options. ex: with pull you can force the download of the files as in the server. Or with push you can force to upload the as in the host.

The push-pull mode is very complicated to implement. You need to implement a software similar to git. If you have this need, you can directly use git to manage your files.

**Comment by Alt-er** [comment]
> Personally, I just resolve my problems renaming and deleting files. For something more general, I don't like the idea, but you can make the sync case-insensitive.

I did think about using force case insensitivity to solve this problem, but this is a breaking update, so I didn't do that because maybe other people's devices are case sensitive, so after they upgrade the version It may cause files with the same name to overwrite each other, thus losing data, so I just added a prompt, after all, the data is the most important.

Under normal circumstances, I think there are very few cases of the same file name, so it should be acceptable to handle it manually.

**Comment by martin-arg** [comment]
> Under normal circumstances, I think there are very few cases of the same file name, so it should be acceptable to handle it manually.

Yes you are right.

Something I discover testing and renaming my files is that android is not case-sensitive. I change my Windows folder to ve case-insensitive, so duplicate files appeared and I consolidate my files. So I was happy, but when I sync with my android devices. Every problem appeared again. It was a surprise.

**Comment by Alt-er** [comment]
Still have problems that cannot be solved?

**Comment by martin-arg** [comment]
Not with this
