### ISSUE TITLE
Long loading times when starting obsidian

### ISSUE THREAD

**Issue by martin-arg** [Alt-er/obsidian-sync-share#19]
For some time now, I have been having very long start-up times for Obsidian on my mobile phone and computer. And every time the Obsidian index file windows appear. In my phone the startup time is more than a minute, in the PC it is almost 10 seconds. In the phone this is the only plugin I have installed and in both devices when I disable the plugin I have virtually no wait time for Obsidian. I cannot say if this starts with the latest plugin update, if you have a copy of version 1.20 I can test it.

**Comment by Alt-er** [comment]
This problem does exist and has been fixed in the latest version. Please update the plug-in

**Comment by martin-arg** [comment]
Everything works perfect
