### ISSUE TITLE
"Invalid server URL. Please enter a valid URL." Error

### ISSUE THREAD

**Issue by ethereal-and-co** [Alt-er/obsidian-sync-share#23]
#Hi
I'm having trouble with using my own storage space, found here: [https://etherealandco.b-cdn.net/obsidian](https://etherealandco.b-cdn.net/obsidian) (it 404's because there are no direct files to link to), I'm not sure if I've just set this up wrong, or misunderstood what exactly I'm meant to do. The provider I'm using is bunny.net with a google login, do I need to provide any other information before I can get some help? Thank you *so* much for this plug-in!

**Comment by Alt-er** [comment]
"Invalid server URL. Please enter a valid URL."
---
It should be similar to this.

![image](https://github.com/Alt-er/obsidian-sync-share/assets/18004903/28f51483-3fd7-4746-82bd-0031024fe6e3)

**Comment by Alt-er** [comment]
Secondary paths cannot be used

**Comment by ethereal-and-co** [comment]
Secondary path? As far as I'm aware (sorry I'm kind of new to using URLs) the link I'm using is the direct path link to my cdn & storage

**Comment by Alt-er** [comment]
The backend service address must only include the protocol and domain name, such as:
https://www.xxx.com

You cannot use a secondary path, like:
https://www.xxx.com/xxx

**Comment by ethereal-and-co** [comment]
Thanks so much! Fixed that so now it just ends in .net, my new struggle is using the login? I put a username & a password but it says "Load failed", I read the information and it says it'll provide a password if there is none, but it's asking for a password or a valid username no matter what I do, if I'm understanding right I need to use my bunny.net login? But I'm using google login & an email isn't a valid username, so sorry to keep bothering you! And thanks in advance!

**Comment by Alt-er** [comment]
The username and password are automatically created. If a username has not been logged in before, it will be automatically created. For example, if you enter username: aaaaa and password: bbbbb, the account aaaaa will be automatically created. If an error message is prompted during login, there should be a problem with your backend service. Please verify whether your backend service is normal.

**Comment by ethereal-and-co** [comment]
There's no problem with my service that I can see, every time I press the login button my service gives a status 404 for the path "... .net/robots.txt" (which doesn't exist on my service), but the link I gave is only to "... .net" with nothing in the end? (The only built in errors I should be seeing on my service are 403's or 405's for manually blocked root path access to my files or blocked POST requests respectively)

(Also every single username I've tried says invalid password, etherealandsystem, ethyn_no, etherealandco, etc, I can't tell if these usernames already exist or not from the invalid password error I receive)

So sorry to keep bothering you, thank you so much for helping me out

**Comment by Alt-er** [comment]
The plugin will not access `robots.txt` when logging in, it should be accessed by other clients

You can use the following command to verify whether your backend service is normal, use cmd under Windows, or iTerm under MacOS to execute the following command:
`curl -X POST https://xxx.yourhost.net/api/user/login `

Return result:

![image](https://github.com/Alt-er/obsidian-sync-share/assets/18004903/c776262b-88b1-4578-8bfb-de87d1007e10)

**Comment by ethereal-and-co** [comment]
Sorry for responding a few days late, I was waiting on my laptop to arrive before I could try this; I'm getting a 400 bad request error, not sure why, I'm going to assume it's something bunny.net itself is doing, I'll continue to investigate everything myself and hopefully I'll find something lmao

Thank you so much for all your help!! I'll close this since it seems to be an error on my side alone 😆
