### ISSUE TITLE
add note sync to quick action?

### ISSUE THREAD

**Issue by wangweitung** [Alt-er/obsidian-sync-share#3]
![Screenshot_2023-09-08-18-32-17-029_md obsidian](https://github.com/Alt-er/obsidian-sync-share/assets/8080125/debc3c72-1dd6-4485-a28f-fba81816eca8)

**Comment by Alt-er** [comment]
Why not enable automatic synchronization? My understanding is that manual synchronization is not a common operation, so it's not added to the quick action

**Comment by wangweitung** [comment]
When muti devices turn on automatically syncing ,it easily get conflict showing ”another device is syncing ".

Maybe I should set different sync period on each device to avoid conflicts.
