### ISSUE TITLE
Hide top bar while scrolling?

### ISSUE THREAD

**Issue by wangweitung** [Alt-er/obsidian-sync-share#5]
Could the head bar hiding while scrolling?

![Screenshot_2023-09-12-09-43-19-814_com.tencent.mm.jpg](https://github.com/Alt-er/obsidian-sync-share/assets/8080125/6958c304-a7ad-456a-a321-5ebc08a1ec41)

**Comment by Alt-er** [comment]
This feature will be added in a later version, it wasn't done before because we were considering which mode to use. 
1. hide the header when scrolling down, and show it when scrolling up.
2. don't fix the position of the header, follow the scrolling bar.

**Comment by wangweitung** [comment]
> 

prefer the No.2 option

**Comment by wangweitung** [comment]
> This feature will be added in a later version, it wasn't done before because we were considering which mode to use.
> 
>     1. hide the header when scrolling down, and show it when scrolling up.
> 
>     2. don't fix the position of the header, follow the scrolling bar.

prefer the No.2 option

**Comment by Alt-er** [comment]
A new version has been released, please update the plugin.

**Comment by wangweitung** [comment]
> A new version has been released, please update the plugin.

It now works perfect for me. Thanks for your great work.

By the way ,  I'm still waiting for the permanent link which means share the link once and update the content freely.

**Comment by Alt-er** [comment]
> By the way , I'm still waiting for the permanent link which means share the link once and update the content freely.

This feature is included in this update, allowing you to overwrite previous links with the latest note contents

**Comment by wangweitung** [comment]
> > By the way , I'm still waiting for the permanent link which means share the link once and update the content freely.
> 
> This feature is included in this update, allowing you to overwrite previous links with the latest note contents

I find the button by trying around.  Thanks again!

![2023 09 13164349](https://github.com/Alt-er/obsidian-sync-share/assets/8080125/3668f503-c086-4813-9d66-bd1916f8e1ae)

**Comment by wangweitung** [comment]
> > > By the way , I'm still waiting for the permanent link which means share the link once and update the content freely.
> > 
> > 
> > This feature is included in this update, allowing you to overwrite previous links with the latest note contents
> 
> I find the button by trying around. Thanks again!
> 
> ![2023 09 13164349](https://user-images.githubusercontent.com/8080125/267592842-3668f503-c086-4813-9d66-bd1916f8e1ae.png)

could this be a default setting? because updating related files is just so annoying. 😂

**Comment by Alt-er** [comment]
default setting? Can you be more specific about the scenario?

**Comment by wangweitung** [comment]
> default setting? Can you be more specific about the scenario?

if the 123.md file was updated , the shared web could also be updated automatically by keeping the url unchanged....

without clicking and resharing...

**Comment by Alt-er** [comment]
> > default setting? Can you be more specific about the scenario?
> 
> if the 123.md file was updated , the shared web could also be updated automatically by keeping the url unchanged....
> 
> without clicking and resharing...

There is no way to automatically update now. You must click the `Overwrite` button to update the content under this link. Each share is a copy of the current state. Some scenes do require real-time updates, but in most cases the note content should be prepared. Update later. If you update in real time, others may see the content you are editing.

**Comment by wangweitung** [comment]
> > > default setting? Can you be more specific about the scenario?
> > 
> > 
> > if the 123.md file was updated , the shared web could also be updated automatically by keeping the url unchanged....
> > without clicking and resharing...
> 
> There is no way to automatically update now. You must click the `Overwrite` button to update the content under this link. Each share is a copy of the current state. Some scenes do require real-time updates, but in most cases the note content should be prepared. Update later. If you update in real time, others may see the content you are editing.

understood
