### ISSUE TITLE
could the metadata be well displayed or ignored？

### ISSUE THREAD

**Issue by wangweitung** [Alt-er/obsidian-sync-share#7]
![image](https://github.com/Alt-er/obsidian-sync-share/assets/8080125/21a86e06-69fd-4fac-a1cc-3b6280ad1181)

**Comment by Alt-er** [comment]
What's this?

**Comment by wangweitung** [comment]
> What's this?

it is metadata in a .md file, like the file below:

![图片](https://github.com/Alt-er/obsidian-sync-share/assets/8080125/cdd603af-382e-4479-addd-fba95623cc72)

**Comment by Alt-er** [comment]
This does not belong to the standard syntax of markdown, so it cannot be processed. You can consider whether you can hide it with an html tag.

```html
<div style="display:none">
...
</div>
```

**Comment by wangweitung** [comment]
> This does not belong to the standard syntax of markdown, so it cannot be processed. You can consider whether you can hide it with an html tag.
> 
> ```
> <div style="display:none">
> ...
> </div>
> ```

thanks!
