### ISSUE TITLE
Is there a file size limit?

### ISSUE THREAD

**Issue by nikpelgr** [Alt-er/obsidian-sync-share#9]
Hi,
just installed the app using docker-compose and synced a couple of devices. 
It seems that some files are missing. Probably because there is a file size limit. For example, I had a zip file in the root with 1.4Gb size and it wasn't synced at all. Size 0KB

Is this configurable ?

**Comment by Alt-er** [comment]
> Hi, just installed the app using docker-compose and synced a couple of devices. It seems that some files are missing. Probably because there is a file size limit. For example, I had a zip file in the root with 1.4Gb size and it wasn't synced at all. Size 0KB
> 
> Is this configurable ?

The plug-in does not limit the size of synchronized files, but the backend limits uploaded files to no more than 10GB. If reverse proxy software such as nginx is used, the size of uploaded files may be limited by these software.
